# Generated by Django 4.2.7 on 2023-11-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(upload_to='Gallery')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
